import { Box, Typography } from '@mui/material'
import React from 'react'

export const MainTextArea = () => {
    return (
        <>
            <Box sx={{
                backgroundColor: '#fafafa',
                mt: 2,
            }}>
                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    Flipkart: The One-stop Shopping Destination
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                </Typography>
                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    Flipkart Plus
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                </Typography>

                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    No Cost EMI
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                </Typography>

                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    EMI on Debits Cards
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000.
                </Typography>
                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    Mobile Exchange Offers
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                </Typography>
                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    Mobile Phones
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.This electronic record.
                </Typography>

                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    Electronic Devices and Accessories
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                </Typography>

                <Typography sx={{
                    fontSize: '18px',
                    fontWeight: 600,
                    color: 'grey',
                    pt: 4, pl: 3, mb: 2
                }}>
                    Large Appliances
                </Typography>

                <Typography sx={{
                    fontSize:'15px',
                    color: 'grey',
                    pl: 3, pr: 4,
                }}>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                    under as applicable and the amended provisions pertaining to electronic records in various statutes
                    as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                    system and does not require any physical or digital signatures.
                </Typography>

            </Box>

        </>
    )
}

