import { Box, Container, Paper, Typography } from '@mui/material'
import React from 'react'

export default function Terms() {
    return (
        <>
            <Container maxWidth='md'>
                <Paper elevation={0} sx={{
                    borderRadius: '0px',
                    mt: 12,
                }}>
                    <Box sx={Styles.box}>
                        <Typography sx={Styles.headingText}>Flipkart Terms of Use</Typography>
                        <Typography sx={Styles.normalText}>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                            under as applicable and the amended provisions pertaining to electronic records in various statutes
                            as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                            system and does not require any physical or digital signatures.
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
                            (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
                            and Terms of Use for access or usage of domain name [www.flipkart.com] (“Website”), including the related
                            mobile site and mobile application (hereinafter referred to as “Platform”)
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            The Platform is owned by Flipkart Internet Private Limited, a company incorporated under the Companies Act, 1956
                            with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road,
                            Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India and its branch offices at 2nd Floor,
                            Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-560103,
                            Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India
                            (hereinafter referred to as "Flipkart").
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            Your use of the Platform and services and tools are governed by the following terms and 
                            conditions ("Terms of Use") as applicable to the Platform including the applicable 
                            policies which are incorporated herein by way of reference. If You transact on the 
                            Platform, You shall be subject to the policies that are applicable to the Platform 
                            for such transaction. By mere use of the Platform, You shall be contracting with Flipkart
                             Internet Private Limited and these terms and conditions including the policies
                              constitute Your binding obligations, with Flipkart.
                        </Typography>
                        <Typography sx={Styles.normalText}>
                           For the purpose of these Terms of Use, wherever the context so requires "You" or "User"
                            shall mean any natural or legal person who has agreed to become a buyer on the Platform
                             by providing Registration Data while registering on the Platform as Registered User 
                             using the computer systems. Flipkart allows the User to surf the Platform or making 
                             purchases without registering on the Platform. The term "We", "Us", "Our" shall mean 
                             Flipkart Internet Private Limited.
                        </Typography>
                        <Typography sx={{
                            fontSize: '13px',
                            mb: 2,
                        }}>Membership Eligibilty </Typography>
                        <Typography sx={Styles.normalText}>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                            under as applicable and the amended provisions pertaining to electronic records in various statutes
                            as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                            system and does not require any physical or digital signatures.
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
                            (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
                            and Terms of Use for access or usage of domain name [www.flipkart.com] (“Website”), including the related
                            mobile site and mobile application (hereinafter referred to as “Platform”)
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            The Platform is owned by Flipkart Internet Private Limited, a company incorporated under the Companies Act, 1956
                            with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road,
                            Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India and its branch offices at 2nd Floor,
                            Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-560103,
                            Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India
                            (hereinafter referred to as "Flipkart").
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            Your use of the Platform and services and tools are governed by the following terms and 
                            conditions ("Terms of Use") as applicable to the Platform including the applicable 
                            policies which are incorporated herein by way of reference. If You transact on the 
                            Platform, You shall be subject to the policies that are applicable to the Platform 
                            for such transaction. By mere use of the Platform, You shall be contracting with Flipkart
                             Internet Private Limited and these terms and conditions including the policies
                              constitute Your binding obligations, with Flipkart.
                        </Typography>
                        <Typography sx={Styles.normalText}>
                           For the purpose of these Terms of Use, wherever the context so requires "You" or "User"
                            shall mean any natural or legal person who has agreed to become a buyer on the Platform
                             by providing Registration Data while registering on the Platform as Registered User 
                             using the computer systems. Flipkart allows the User to surf the Platform or making 
                             purchases without registering on the Platform. The term "We", "Us", "Our" shall mean 
                             Flipkart Internet Private Limited.
                        </Typography>
                        <Typography sx={{
                            fontSize: '13px',
                            mb: 2,
                        }}>Your Account and Registration Obligations</Typography>
                        <Typography sx={Styles.normalText}>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules there
                            under as applicable and the amended provisions pertaining to electronic records in various statutes
                            as amended by the Information Technology Act, 2000. This electronic record is generated by a computer
                            system and does not require any physical or digital signatures.
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
                            (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
                            and Terms of Use for access or usage of domain name [www.flipkart.com] (“Website”), including the related
                            mobile site and mobile application (hereinafter referred to as “Platform”)
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            The Platform is owned by Flipkart Internet Private Limited, a company incorporated under the Companies Act, 1956
                            with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road,
                            Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India and its branch offices at 2nd Floor,
                            Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-560103,
                            Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India
                            (hereinafter referred to as "Flipkart").
                        </Typography>
                        <Typography sx={Styles.normalText}>
                            Your use of the Platform and services and tools are governed by the following terms and 
                            conditions ("Terms of Use") as applicable to the Platform including the applicable 
                            policies which are incorporated herein by way of reference. If You transact on the 
                            Platform, You shall be subject to the policies that are applicable to the Platform 
                            for such transaction. By mere use of the Platform, You shall be contracting with Flipkart
                             Internet Private Limited and these terms and conditions including the policies
                              constitute Your binding obligations, with Flipkart.
                        </Typography>
                        <Typography sx={Styles.normalText}>
                           For the purpose of these Terms of Use, wherever the context so requires "You" or "User"
                            shall mean any natural or legal person who has agreed to become a buyer on the Platform
                             by providing Registration Data while registering on the Platform as Registered User 
                             using the computer systems. Flipkart allows the User to surf the Platform or making 
                             purchases without registering on the Platform. The term "We", "Us", "Our" shall mean 
                             Flipkart Internet Private Limited.
                        </Typography>

                        

                    </Box>

                </Paper>
            </Container>
        </>
    )
}

const Styles={
    box:{
        padding: '2rem 2rem 1rem 2rem',
        width: '90%',
    },
    headingText:{
        fontSize: '14px',
        fontWeight: 600,
        mb: 3,
    },
    normalText:{
        fontSize: '13px',
        whiteSpace: 'normal',
        mb: 1,
    },
}